version: "3"
services:

  # zookeeper. Ref.: https://zookeeper.apache.org
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  # kafka server. Ref.: https://kafka.apache.org
  kafka:
    image: confluentinc/cp-kafka:5.0.1
    hostname: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper
